name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Disable CI error on warnings
        run: unset CI

      - name: Set up Git user
        run: |
          git config --global user.name "VishalGowlikar"
          git config --global user.email "vishalkishnn18886@gmail.com"

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/VishalGowlikar/portfolio.git
          npm run deploy
